import { ROAD } from '../../config';
import type { Track } from '../../systems/road/Track';
import { TrackBuilder } from '../../systems/road/TrackBuilder';
import { NEON_BOULEVARD } from '../themes/neonBoulevard';
import { CURVE, FORK_APPROACH, HILL, SIDE, STAGE_CHECKPOINT_SECONDS, START_STRAIGHT } from './shapes';

/** Leg 3: the neon strip to the pier. Flat, fast S-bends between towers and billboards. */
export function buildNeonBoulevard(): Track {
  const { tall, low, building, obstacle } = NEON_BOULEVARD.scenery;
  return new TrackBuilder(ROAD.segmentLength)
    .straight(START_STRAIGHT)
    .scenery(tall, { every: 7, offsets: [-SIDE.near, SIDE.near] })
    .straight(35)
    .checkpoint(STAGE_CHECKPOINT_SECONDS)
    .scenery(tall, { every: 7, offsets: [-SIDE.near, SIDE.near] })
    .straight(100)
    .scenery(tall, { every: 7, offsets: [-SIDE.near, SIDE.near] })
    .scenery(building, { every: 12, offsets: [-SIDE.far, SIDE.far] })
    .curve(70, CURVE.medium)
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 4 })
    .scenery(low, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .curve(70, -CURVE.medium)
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 4 })
    .scenery(obstacle, { every: 14, offsets: [SIDE.far] })
    .straight(110)
    .scenery(tall, { every: 7, offsets: [-SIDE.near, SIDE.near] })
    .scenery(building, { every: 10, offsets: [-SIDE.far, SIDE.far] })
    .curve(70, -CURVE.sharp)
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 5 })
    .scenery(low, { every: 5, offsets: [-SIDE.near] })
    .curve(70, CURVE.sharp)
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 5 })
    .scenery(obstacle, { every: 12, offsets: [-SIDE.far] })
    .straight(120)
    .scenery(tall, { every: 7, offsets: [-SIDE.near, SIDE.near] })
    .scenery(building, { every: 12, offsets: [-SIDE.far, SIDE.far] })
    .hill(40, HILL.low)
    .scenery(low, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .hill(40, -HILL.low)
    .scenery(tall, { every: 7, offsets: [-SIDE.near, SIDE.near] })
    .curve(80, CURVE.medium)
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 4 })
    .scenery(obstacle, { every: 12, offsets: [SIDE.far] })
    .curve(80, -CURVE.medium)
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 4 })
    .scenery(building, { every: 12, offsets: [-SIDE.far] })
    .straight(120)
    .scenery(tall, { every: 7, offsets: [-SIDE.near, SIDE.near] })
    .scenery(building, { every: 10, offsets: [SIDE.far] })
    .curve(70, CURVE.sharp)
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 5 })
    .scenery(low, { every: 5, offsets: [SIDE.near] })
    .curve(70, -CURVE.sharp)
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 5 })
    .scenery(obstacle, { every: 12, offsets: [SIDE.far] })
    .straight(100)
    .scenery(tall, { every: 7, offsets: [-SIDE.near, SIDE.near] })
    .scenery(building, { every: 12, offsets: [-SIDE.far, SIDE.far] })
    .curve(80, -CURVE.medium)
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 4 })
    .scenery(low, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .curve(80, CURVE.medium)
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 4 })
    .scenery(tall, { every: 7, offsets: [-SIDE.near, SIDE.near] })
    .straight(110)
    .scenery(building, { every: 10, offsets: [-SIDE.far, SIDE.far] })
    .scenery(tall, { every: 7, offsets: [-SIDE.near, SIDE.near] })
    .curve(70, CURVE.gentle)
    .scenery(obstacle, { every: 12, offsets: [-SIDE.far] })
    .straight(80)
    .scenery(tall, { every: 7, offsets: [-SIDE.near, SIDE.near] })
    .straight(FORK_APPROACH)
    .scenery(tall, { every: 7, offsets: [-SIDE.near, SIDE.near] })
    .finish()
    .scenery(tall, { every: 7, offsets: [-SIDE.near, SIDE.near] })
    .build();
}
