import { ROAD } from '../../config';
import type { Track } from '../../systems/road/Track';
import { TrackBuilder } from '../../systems/road/TrackBuilder';
import { PINEWOOD_PASS } from '../themes/pinewoodPass';
import { CURVE, FORK_APPROACH, HILL, SIDE, STAGE_CHECKPOINT_SECONDS, START_STRAIGHT } from './shapes';

/** Leg 3: up through the forest to the summit lodge. Climbing switchbacks between the pines. */
export function buildPinewoodPass(): Track {
  const { tall, low, building, obstacle } = PINEWOOD_PASS.scenery;
  return new TrackBuilder(ROAD.segmentLength)
    .straight(START_STRAIGHT)
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .straight(35)
    .checkpoint(STAGE_CHECKPOINT_SECONDS)
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .road(90, { curve: CURVE.medium, rise: HILL.medium })
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 4 })
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.far] })
    .road(90, { curve: -CURVE.sharp, rise: HILL.medium })
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 5 })
    .scenery(tall, { every: 5, offsets: [-SIDE.far, SIDE.near] })
    .straight(50)
    .scenery(building, { every: 20, offsets: [SIDE.far] })
    .scenery(low, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .road(90, { curve: CURVE.sharp, rise: HILL.low })
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 5 })
    .scenery(obstacle, { every: 9, offsets: [-SIDE.near, SIDE.far] })
    .road(80, { curve: -CURVE.medium, rise: -HILL.low })
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 4 })
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .hill(80, HILL.high)
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .curve(80, CURVE.medium)
    .scenery(building, { every: 16, offsets: [-SIDE.far] })
    .scenery(low, { every: 5, offsets: [SIDE.near] })
    .road(90, { curve: -CURVE.sharp, rise: HILL.medium })
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 5 })
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.far] })
    .straight(60)
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .road(90, { curve: CURVE.sharp, rise: -HILL.medium })
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 5 })
    .scenery(obstacle, { every: 10, offsets: [SIDE.near] })
    .curve(70, -CURVE.gentle)
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .road(90, { curve: CURVE.medium, rise: HILL.medium })
    .scenery(building, { every: 18, offsets: [SIDE.far] })
    .scenery(low, { every: 5, offsets: [-SIDE.near] })
    .road(80, { curve: -CURVE.medium, rise: HILL.low })
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 4 })
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .straight(70)
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .road(90, { curve: CURVE.sharp, rise: HILL.medium })
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 5 })
    .scenery(obstacle, { every: 9, offsets: [-SIDE.far, SIDE.near] })
    .road(90, { curve: -CURVE.sharp, rise: -HILL.low })
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 5 })
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.far] })
    .curve(80, CURVE.gentle)
    .scenery(building, { every: 20, offsets: [-SIDE.far, SIDE.far] })
    .hill(80, HILL.high)
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .straight(80)
    .scenery(low, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .scenery(building, { every: 25, offsets: [SIDE.far] })
    .straight(FORK_APPROACH)
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .finish()
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .build();
}
