import { ROAD } from '../../config';
import type { Track } from '../../systems/road/Track';
import { TrackBuilder } from '../../systems/road/TrackBuilder';
import { REDROCK_DESERT } from '../themes/redrockDesert';
import { CURVE, FORK_APPROACH, HILL, SIDE, STAGE_CHECKPOINT_SECONDS, START_STRAIGHT } from './shapes';

/** Leg 3: across the desert to the observatory. Long straights over rolling dunes, and few bends. */
export function buildRedrockDesert(): Track {
  const { tall, low, building, obstacle } = REDROCK_DESERT.scenery;
  return new TrackBuilder(ROAD.segmentLength)
    .straight(START_STRAIGHT)
    .scenery(tall, { every: 10, offsets: [-SIDE.near, SIDE.far] })
    .straight(35)
    .checkpoint(STAGE_CHECKPOINT_SECONDS)
    .scenery(low, { every: 6, offsets: [-SIDE.near, SIDE.near] })
    .hill(60, HILL.medium)
    .scenery(tall, { every: 10, offsets: [-SIDE.far, SIDE.near] })
    .hill(60, -HILL.medium)
    .scenery(obstacle, { every: 10, offsets: [-SIDE.near, SIDE.far] })
    .straight(120)
    .scenery(tall, { every: 9, offsets: [-SIDE.near, SIDE.near] })
    .scenery(building, { every: 30, offsets: [SIDE.far] })
    .curve(100, CURVE.gentle)
    .scenery(low, { every: 6, offsets: [-SIDE.near, SIDE.far] })
    .hill(80, HILL.high)
    .scenery(tall, { every: 10, offsets: [-SIDE.near, SIDE.far] })
    .hill(80, -HILL.high)
    .scenery(obstacle, { every: 12, offsets: [SIDE.near] })
    .straight(140)
    .scenery(tall, { every: 9, offsets: [-SIDE.near, SIDE.near] })
    .scenery(building, { every: 35, offsets: [-SIDE.far] })
    .curve(90, -CURVE.medium)
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 4 })
    .scenery(low, { every: 6, offsets: [-SIDE.near, SIDE.near] })
    .hill(60, HILL.medium)
    .scenery(tall, { every: 10, offsets: [SIDE.near] })
    .hill(60, -HILL.medium)
    .scenery(obstacle, { every: 10, offsets: [-SIDE.far, SIDE.far] })
    .straight(150)
    .scenery(tall, { every: 9, offsets: [-SIDE.near, SIDE.near] })
    .scenery(building, { every: 30, offsets: [SIDE.far] })
    .curve(100, CURVE.medium)
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 4 })
    .scenery(low, { every: 6, offsets: [SIDE.near] })
    .road(90, { curve: -CURVE.gentle, rise: HILL.low })
    .scenery(tall, { every: 10, offsets: [-SIDE.near, SIDE.far] })
    .road(90, { curve: CURVE.gentle, rise: -HILL.low })
    .scenery(obstacle, { every: 12, offsets: [SIDE.near] })
    .straight(130)
    .scenery(tall, { every: 9, offsets: [-SIDE.near, SIDE.near] })
    .scenery(building, { every: 26, offsets: [-SIDE.far, SIDE.far] })
    .hill(80, HILL.high)
    .scenery(low, { every: 6, offsets: [-SIDE.near, SIDE.near] })
    .hill(80, -HILL.high)
    .scenery(tall, { every: 10, offsets: [-SIDE.far, SIDE.near] })
    .curve(90, -CURVE.sharp)
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 5 })
    .scenery(obstacle, { every: 10, offsets: [-SIDE.near] })
    .straight(160)
    .scenery(tall, { every: 9, offsets: [-SIDE.near, SIDE.near] })
    .scenery(building, { every: 40, offsets: [SIDE.far] })
    .curve(90, CURVE.gentle)
    .scenery(low, { every: 6, offsets: [-SIDE.near, SIDE.far] })
    .straight(FORK_APPROACH)
    .scenery(tall, { every: 8, offsets: [-SIDE.near, SIDE.near] })
    .finish()
    .scenery(tall, { every: 8, offsets: [-SIDE.near, SIDE.near] })
    .build();
}
