import { ROAD } from '../../config';
import type { Track } from '../../systems/road/Track';
import { TrackBuilder } from '../../systems/road/TrackBuilder';
import { SUNSET_COAST } from '../themes/sunsetCoast';
import { CURVE, FORK_APPROACH, FORK_LENGTH, HILL, SIDE, START_STRAIGHT } from './shapes';

/** Leg 1: the coast road out of Port Calla. Flowing bends and rolling hills, lined with palms. */
export function buildSunsetCoast(): Track {
  const { tall, low, building, obstacle } = SUNSET_COAST.scenery;
  return new TrackBuilder(ROAD.segmentLength)
    .straight(START_STRAIGHT)
    .scenery(tall, { every: 6, offsets: [-SIDE.near, SIDE.near] })
    .straight(35)
    .scenery(low, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .curve(80, CURVE.gentle)
    .scenery(tall, { every: 6, offsets: [-SIDE.near, SIDE.near] })
    .hill(60, HILL.medium)
    .scenery(low, { every: 5, offsets: [-SIDE.near, SIDE.far] })
    .scenery(building, { every: 20, offsets: [SIDE.far] })
    .curve(90, -CURVE.medium)
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 4 })
    .scenery(obstacle, { every: 8, offsets: [-SIDE.near, SIDE.far] })
    .straight(60)
    .scenery(tall, { every: 6, offsets: [-SIDE.near, SIDE.near] })
    .road(100, { curve: CURVE.sharp, rise: -HILL.medium })
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 5 })
    .scenery(tall, { every: 8, offsets: [SIDE.near] })
    .hill(80, HILL.high)
    .scenery(low, { every: 4, offsets: [-SIDE.near, SIDE.near] })
    .curve(70, -CURVE.gentle)
    .scenery(building, { every: 16, offsets: [-SIDE.far, SIDE.far] })
    .hill(80, -HILL.high)
    .scenery(tall, { every: 10, offsets: [-SIDE.far] })
    .scenery(low, { every: 5, offsets: [SIDE.near] })
    .straight(80)
    .scenery(tall, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .curve(100, CURVE.medium)
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 4 })
    .scenery(obstacle, { every: 10, offsets: [SIDE.far] })
    .road(90, { curve: -CURVE.sharp, rise: HILL.low })
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 5 })
    .scenery(tall, { every: 8, offsets: [-SIDE.near] })
    .straight(50)
    .scenery(building, { every: 12, offsets: [SIDE.far] })
    .curve(120, CURVE.gentle)
    .scenery(tall, { every: 6, offsets: [-SIDE.near, SIDE.near] })
    .hill(60, -HILL.medium)
    .scenery(low, { every: 5, offsets: [-SIDE.near, SIDE.far] })
    .road(80, { curve: CURVE.medium, rise: HILL.medium })
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 4 })
    .scenery(obstacle, { every: 8, offsets: [SIDE.near] })
    .curve(80, -CURVE.medium)
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 4 })
    .scenery(tall, { every: 7, offsets: [-SIDE.near] })
    .straight(100)
    .scenery(tall, { every: 6, offsets: [-SIDE.near, SIDE.near] })
    .scenery(building, { every: 25, offsets: [-SIDE.far] })
    .road(100, { curve: CURVE.sharp, rise: -HILL.low })
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 5 })
    .scenery(low, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .curve(80, -CURVE.gentle)
    .scenery(tall, { every: 8, offsets: [SIDE.near] })
    .hill(80, HILL.high)
    .scenery(tall, { every: 6, offsets: [-SIDE.near, SIDE.near] })
    .straight(60)
    .scenery(obstacle, { every: 10, offsets: [-SIDE.far, SIDE.far] })
    .road(100, { curve: -CURVE.medium, rise: -HILL.high })
    .scenery('signLeft', { every: 4, offsets: [SIDE.verge], count: 4 })
    .scenery(low, { every: 5, offsets: [-SIDE.near, SIDE.near] })
    .curve(120, CURVE.medium)
    .scenery('signRight', { every: 4, offsets: [-SIDE.verge], count: 4 })
    .scenery(tall, { every: 6, offsets: [-SIDE.near, SIDE.near] })
    .straight(80)
    .scenery(building, { every: 20, offsets: [-SIDE.far, SIDE.far] })
    .straight(FORK_APPROACH)
    .scenery(tall, { every: 6, offsets: [-SIDE.near, SIDE.near] })
    .fork(FORK_LENGTH)
    .scenery(tall, { every: 6, offsets: [-SIDE.near, SIDE.near] })
    .end()
    .scenery(tall, { every: 6, offsets: [-SIDE.near, SIDE.near] })
    .build();
}
