import type { Palette, PixelMap } from '@shared/pixel-art/pixelMap';

/** Scenery for the night-time stages: the harbour and the neon-lit boulevard. */

/** A street lamp with a lit head each side of the pole. */
export const LAMP: PixelMap = [
  '.....lllll......lllll.....',
  '....lLLLLLl....lLLLLLl....',
  '....kkkkkkkkkkkkkkkkkk....',
  '...........kkkk...........',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '............kk............',
  '..........kkkkkk..........',
];

/** An iron mooring bollard on the quay. */
export const BOLLARD: PixelMap = [
  '.kkkkkkkk.',
  'kkkkkkkkkk',
  '..kkkkkk..',
  '..yyyyyy..',
  '..kkkkkk..',
  '..kkkkkk..',
  '..kkkkkk..',
  '.kkkkkkkk.',
];

/** Shipping crates, two on the ground and one on top. */
export const CRATES: PixelMap = [
  '......kkkkkkkkkkkk......',
  '......koooOoooOook......',
  '......kooOoooOoook......',
  '......koOoooOoooOk......',
  '......kOoooOoooOok......',
  '......koooOoooOook......',
  '......kooOoooOoook......',
  '......koOoooOoooOk......',
  '......kkkkkkkkkkkk......',
  'kkkkkkkkkkkkkkkkkkkkkkkk',
  'kbbbBbbbBbbkkoooOoooOook',
  'kbbBbbbBbbbkkooOoooOoook',
  'kbBbbbBbbbBkkoOoooOoooOk',
  'kBbbbBbbbBbkkOoooOoooOok',
  'kbbbBbbbBbbkkoooOoooOook',
  'kbbBbbbBbbbkkooOoooOoook',
  'kbBbbbBbbbBkkoOoooOoooOk',
  'kkkkkkkkkkkkkkkkkkkkkkkk',
];

/** A harbour warehouse with a shutter door and two lit windows. */
export const WAREHOUSE: PixelMap = [
  '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  'kwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwk',
  'kwwWyyyyyywwWwwWwwWwwWwwWwwWwwWwwWwwWwyyyyyywWwk',
  'kwwWyyyyyywwWwwWwwWwwWwwWwwWwwWwwWwwWwyyyyyywWwk',
  'kwwWyyyyyywwWwwWwwWwwWwwWwwWwwWwwWwwWwyyyyyywWwk',
  'kwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWkkkkkkkkkkkkkkkkwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWksssssssssssssskwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWkSSSSSSSSSSSSSSkwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWksssssssssssssskwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWkSSSSSSSSSSSSSSkwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWksssssssssssssskwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWkSSSSSSSSSSSSSSkwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWksssssssssssssskwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWkSSSSSSSSSSSSSSkwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWksssssssssssssskwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWkSSSSSSSSSSSSSSkwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWksssssssssssssskwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWkSSSSSSSSSSSSSSkwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWksssssssssssssskwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWkSSSSSSSSSSSSSSkwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWksssssssssssssskwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWkSSSSSSSSSSSSSSkwWwwWwwWwwWwwWwk',
  'kwwWwwWwwWwwWwwWksssssssssssssskwWwwWwwWwwWwwWwk',
];

/** A tower block at night, some windows lit and some dark, with an aerial light on top. */
export const TOWER: PixelMap = [
  '...................rr...................',
  '...................rr...................',
  '...................kk...................',
  '...................kk...................',
  '...................kk...................',
  '...................kk...................',
  '...................kk...................',
  '...................kk...................',
  '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbnnbbyybbnnbbnnbbyybbnnbbyybbccbBBBBBk',
  'kbbnnbbyybbnnbbnnbbyybbnnbbyybbccbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbnnbbyybbccbbnnbbnnbbnnbbnnbbyybBBBBBk',
  'kbbnnbbyybbccbbnnbbnnbbnnbbnnbbyybBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbccbbnnbbyybbccbbnnbbnnbbnnbbnnbBBBBBk',
  'kbbccbbnnbbyybbccbbnnbbnnbbnnbbnnbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbnnbbnnbbyybbyybbyybbnnbbyybbnnbBBBBBk',
  'kbbnnbbnnbbyybbyybbyybbnnbbyybbnnbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbyybbnnbbyybbnnbbnnbbyybbnnbbyybBBBBBk',
  'kbbyybbnnbbyybbnnbbnnbbyybbnnbbyybBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbccbbnnbbyybbyybbyybbccbbnnbbnnbBBBBBk',
  'kbbccbbnnbbyybbyybbyybbccbbnnbbnnbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbnnbbnnbbyybbyybbnnbbccbbnnbbyybBBBBBk',
  'kbbnnbbnnbbyybbyybbnnbbccbbnnbbyybBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbnnbbnnbbyybbyybbyybbyybbyybbnnbBBBBBk',
  'kbbnnbbnnbbyybbyybbyybbyybbyybbnnbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbccbbnnbbccbbyybbccbbccbbnnbbyybBBBBBk',
  'kbbccbbnnbbccbbyybbccbbccbbnnbbyybBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbnnbbnnbbnnbbnnbbccbbyybbnnbbyybBBBBBk',
  'kbbnnbbnnbbnnbbnnbbccbbyybbnnbbyybBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbnnbbyybbyybbnnbbyybbnnbbnnbbnnbBBBBBk',
  'kbbnnbbyybbyybbnnbbyybbnnbbnnbbnnbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbccbbccbbyybbnnbbyybbccbbnnbbnnbBBBBBk',
  'kbbccbbccbbyybbnnbbyybbccbbnnbbnnbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbnnbbnnbbyybbyybbyybbnnbbyybbyybBBBBBk',
  'kbbnnbbnnbbyybbyybbyybbnnbbyybbyybBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbnnbbyybbnnbbyybbyybbnnbbyybbnnbBBBBBk',
  'kbbnnbbyybbnnbbyybbyybbnnbbyybbnnbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbnnbbyybbyybbnnbbnnbbyybbccbbccbBBBBBk',
  'kbbnnbbyybbyybbnnbbnnbbyybbccbbccbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbnnbbnnbbnnbbyybbnnbbccbbccbbnnbBBBBBk',
  'kbbnnbbnnbbnnbbyybbnnbbccbbccbbnnbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
  'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbBBBBBk',
];

/** A neon sign on two posts: a pink tube round a cyan star. */
export const NEON_SIGN: PixelMap = [
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  'knnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnk',
  'knmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnk',
  'knmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmnk',
  'knmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmnk',
  'knmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmnk',
  'knmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmnk',
  'knmnnnnnnnnnnnnnncnnnnnnnnnnnnnnnmnk',
  'knmnnnnnnnnnnnnncccnnnnnnnnnnnnnnmnk',
  'knmnnnnnnnncccccccccccccnnnnnnnnnmnk',
  'knmnnnnnnnnnncccccccccnnnnnnnnnnnmnk',
  'knmnnnnnnnnnnncccccccnnnnnnnnnnnnmnk',
  'knmnnnnnnnnnncccnnncccnnnnnnnnnnnmnk',
  'knmnnnnnnnnnccnnnnnnnccnnnnnnnnnnmnk',
  'knmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmnk',
  'knmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmnk',
  'knmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmnk',
  'knmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmnk',
  'knmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmnk',
  'knmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnk',
  'knnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnk',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
  '.....kk......................kk.....',
];

/** Street lamps glow warm yellow on the harbour and hot pink on the boulevard. */
export const LAMP_PALETTE: Palette = { k: '#3a3e52', l: '#f2c84b', L: '#fff4b0' };
export const NEON_LAMP_PALETTE: Palette = { k: '#2e2440', l: '#ff4ad0', L: '#ffc0f0' };
export const BOLLARD_PALETTE: Palette = { k: '#2a2a34', y: '#f2c230' };
export const CRATES_PALETTE: Palette = { k: '#1b1b22', o: '#d86a2a', O: '#a84e1e', b: '#2a6ab8', B: '#1e4e8a' };
export const WAREHOUSE_PALETTE: Palette = {
  k: '#141824',
  w: '#3a4458',
  W: '#2e3648',
  s: '#4a5268',
  S: '#3a4256',
  y: '#f2c84b',
};
export const TOWER_PALETTE: Palette = {
  k: '#0e0a18',
  b: '#241c38',
  B: '#1a142a',
  y: '#ffd66a',
  c: '#6af0ff',
  n: '#141024',
  r: '#ff3a3a',
};
export const NEON_SIGN_PALETTE: Palette = { k: '#1b1b22', m: '#ff4ad0', c: '#6af0ff', n: '#241034' };
