import type { Palette, PixelMap } from '@shared/pixel-art/pixelMap';

/** Scenery for the open-country stages: canyon, desert and mountain pass. */

/** A pine of four tiers, for Pinewood Pass. */
export const PINE: PixelMap = [
  '............gg............',
  '...........GggG...........',
  '..........gggggg..........',
  '.........GggggggG.........',
  '........gggggggggg........',
  '........GgGggggGgG........',
  '.......ggGggggggGgg.......',
  '......GGGggggggggGGG......',
  '.....GGGGGGGGGGGGGGGG.....',
  '..........gggggg..........',
  '.........GggggggG.........',
  '........gggggggggg........',
  '........GggggggggG........',
  '.......gggGggggGggg.......',
  '......GggGggggggGggG......',
  '.....gggGggggggggGggg.....',
  '.....GgGggggggggggGgG.....',
  '....GGGggggggggggggGGG....',
  '...GGGGGGGGGGGGGGGGGGGG...',
  '........GggggggggG........',
  '.......GggggggggggG.......',
  '.......gggggggggggg.......',
  '......GgggGggggGgggG......',
  '.....ggggGggggggGgggg.....',
  '....GgggGggggggggGgggG....',
  '....gggGggggggggggGggg....',
  '...GggGggggggggggggGggG...',
  '..gggGggggGggggGggggGggg..',
  '..GGGggggGggggggGggggGGG..',
  '.GGGGGGGGGGGGGGGGGGGGGGGG.',
  '......gGggggggggggGg......',
  '.....GGggggggggggggGG.....',
  '.....GggggGggggGggggG.....',
  '....GggggGggggggGggggG....',
  '....ggggGggggggggGgggg....',
  '...GgggGggggggggggGgggG...',
  '...gggGggggggggggggGggg...',
  '..GggGggggGggggGggggGggG..',
  '..ggGggggGggggggGggggGgg..',
  '.GgGggggGggggggggGggggGgG.',
  '.GGggggGggggggggggGggggGG.',
  'GGGGGGGGGGGGGGGGGGGGGGGGGG',
  '...........tTTt...........',
  '...........tTTt...........',
  '...........tTTt...........',
  '...........tTTt...........',
  '...........tTTt...........',
  '...........tTTt...........',
];

/** A saguaro cactus, for Redrock Desert. */
export const CACTUS: PixelMap = [
  '......cccc........',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.cc..cCcccc.......',
  'cCcc.cCcccc.......',
  'cCcc.cCcccc...cc..',
  'cCcc.cCcccc..cCcc.',
  'cCcc.cCcccc..cCcc.',
  'cCcc.cCcccc..cCcc.',
  'cCcc.cCcccc..cCcc.',
  'cCcccccCccc..cCcc.',
  'cCcccccCccc..cCcc.',
  '.cCCCCcCccc..cCcc.',
  '.....cCcccccccCcc.',
  '.....cCcccccccCcc.',
  '.....cCcccCCCCCc..',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '.....cCcccc.......',
  '....ddddddddd.....',
];

/** A butte of layered sandstone, for the canyon and the desert. */
export const CLIFF: PixelMap = [
  '.......LLLRRRdrrrrrrrdddd.......',
  '.....LLLrddddrrrrrrrrrrdddd.....',
  '....LLLrrrrrrrrrrrrrrrrrdddd....',
  '....LLLrrrrrrrrrrrrrrrrrdddd....',
  '.....LLLrrrrrrrrddddrrrdddd.....',
  '....LLLrrrrrrrddRRRRdrrrdddd....',
  '.....LLLdrrrrdRRRRRRRdddddd.....',
  '.....LLLRddddRRRRRRRRRRdddd.....',
  '....LLLRRRRRRRRRRRRRRRRRdddd....',
  '...LLLRRRRRRRRRRRRRRRRRRRdddd...',
  '..LLLdRRRRRRRRRRddddRRRRRRdddd..',
  '.LLLrrdRRRRRRRddrrrrdRRRRRRdddd.',
  '.LLLrrrddRRRRdrrrrrrrddRRRRdddd.',
  '.LLLrrrrrddddrrrrrrrrrrdddddddd.',
  '.LLLrrrrrrrrrrrrrrrrrrrrrrrdddd.',
  '..LLLrrrrrrrrrrrrrrrrrrrrrdddd..',
  '..LLLdrrrrrrrrrrddddrrrrrrdddd..',
  '..LLLRdrrrrrrrddRRRRdrrrrrdddd..',
  '.LLLRRRddrrrrdRRRRRRRddrrrrdddd.',
  'LLLRRRRRRddddRRRRRRRRRRddddRdddd',
  'LLLRRRRRRRRRRRRRRRRRRRRRRRRRdddd',
  'LLLRRRRRRRRRRRRRRRRRRRRRRRRRdddd',
  '.LLLddRRRRRRRRRRddddRRRRRRRdddd.',
  '.LLLrrdRRRRRRRddrrrrdRRRRRRdddd.',
  '..LLLrrddRRRRdrrrrrrrddRRRdddd..',
  '..LLLrrrrddddrrrrrrrrrrddddddd..',
  '..LLLrrrrrrrrrrrrrrrrrrrrrdddd..',
  '.LLLrrrrrrrrrrrrrrrrrrrrrrrdddd.',
  'LLLdddrrrrrrrrrrddddrrrrrrrrdddd',
  'LLLRRRdrrrrrrrddRRRRdrrrrrrrdddd',
  'LLLRRRRddrrrrdRRRRRRRddrrrrddddd',
  '.LLLRRRRRddddRRRRRRRRRRdddddddd.',
  '.LLLRRRRRRRRRRRRRRRRRRRRRRRdddd.',
  '..LLLRRRRRRRRRRRRRRRRRRRRRdddd..',
  '..LLLdRRRRRRRRRRddddRRRRRRdddd..',
  '..LLLrdRRRRRRRddrrrrdRRRRRdddd..',
  '.LLLrrrddRRRRdrrrrrrrddRRRRdddd.',
  'LLLrrrrrrddddrrrrrrrrrrddddrdddd',
  'LLLrrrrrrrrrrrrrrrrrrrrrrrrrdddd',
  'LLLrrrrrrrrrrrrrrrrrrrrrrrrrdddd',
  '.LLLddrrrrrrrrrrddddrrrrrrrdddd.',
  '.LLLRRdrrrrrrrddRRRRdrrrrrrdddd.',
  '..LLLRRddrrrrdRRRRRRRddrrrdddd..',
  '..LLLRRRRddddRRRRRRRRRRddddddd..',
  '..LLLRRRRRRRRRRRRRRRRRRRRRdddd..',
  '.LLLRRRRRRRRRRRRRRRRRRRRRRRdddd.',
  'LLLdddRRRRRRRRRRddddRRRRRRRRdddd',
  'LLLrrrdRRRRRRRddrrrrdRRRRRRRdddd',
  'LLLrrrrddRRRRdrrrrrrrddRRRRddddd',
  '.LLLrrrrrddddrrrrrrrrrrdddddddd.',
  '.LLLrrrrrrrrrrrrrrrrrrrrrrrdddd.',
  '..LLLrrrrrrrrrrrrrrrrrrrrrdddd..',
  '..LLLdrrrrrrrrrrddddrrrrrrdddd..',
  '..LLLRdrrrrrrrddRRRRdrrrrrdddd..',
  '.LLLRRRddrrrrdRRRRRRRddrrrrdddd.',
  'LLLRRRRRRddddRRRRRRRRRRddddRdddd',
];

/** A log cabin with its lamps lit, for Pinewood Pass. */
export const CABIN: PixelMap = [
  '........................ss........',
  '........................ss........',
  '...............RR.......ss........',
  '.............RRRRRR.....ss........',
  '...........RRRRRRRRRR...ss........',
  '.........RRRRRRRRRRRRRR.ss........',
  '.......RRRRRRRRRRRRRRRRRRR........',
  '.....RRRRRRRRRRRRRRRRRRRRRRR......',
  '...RRRRRRRRRRRRRRRRRRRRRRRRRRR....',
  '.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR..',
  'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  '..llllllllllllllllllllllllllllll..',
  '..eLLLLLLLLLLLLLLLLLLLLLLLLLLLLe..',
  '..lllffffffllllllllllllfffffflll..',
  '..eLLfyyyyfLLLLffffLLLLfyyyyfLLe..',
  '..lllfyyyyfllllDDDDllllfyyyyflll..',
  '..eLLfyyyyfLLLLDDDDLLLLfyyyyfLLe..',
  '..lllffffffllllDDDDllllfffffflll..',
  '..eLLLLLLLLLLLLDDDDLLLLLLLLLLLLe..',
  '..lllllllllllllDDDDlllllllllllll..',
  '..eLLLLLLLLLLLLDDDDLLLLLLLLLLLLe..',
  '..lllllllllllllDDDDlllllllllllll..',
  '..eLLLLLLLLLLLLDDDDLLLLLLLLLLLLe..',
];

export const PINE_PALETTE: Palette = { g: '#2f7a3a', G: '#1d5a2a', t: '#6a4424', T: '#4a2e18' };
export const CACTUS_PALETTE: Palette = { c: '#4a9a3a', C: '#2e6a26', d: '#9a7a4a' };
export const CLIFF_PALETTE: Palette = { r: '#c0643a', R: '#a8502e', L: '#e08a5a', d: '#7a3422' };
export const CABIN_PALETTE: Palette = {
  s: '#5a5a66',
  R: '#3a5a3a',
  r: '#24402a',
  l: '#9a6a3a',
  L: '#7e5430',
  e: '#5a3a1e',
  f: '#4a2e18',
  y: '#ffd66a',
  D: '#5a3a1e',
};
